// sigmashake-vcs — failover test
// Failover — source carries error-handling / fallback paths.
// Generated by shared/agent-config/scripts/generate-kind-tests.ts — runtime-free:
// asserts invariants from the project's own files (deterministic, PSU-safe).
import { describe, expect, test } from "bun:test";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");

function readdirSafe(d: string): string[] {
  try {
    return readdirSync(d);
  } catch {
    return [];
  }
}
function collectSrc(): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const e of readdirSafe(dir)) {
      if (e === "node_modules" || e === "dist" || e === "public" || e.startsWith(".")) continue;
      const full = join(dir, e);
      let isDir = false;
      try {
        isDir = statSync(full).isDirectory();
      } catch {
        continue;
      }
      if (isDir) walk(full);
      else if (/\.(ts|tsx|js|mjs|cjs)$/.test(full) && !/\.(test|spec)\./.test(full)) out.push(full);
    }
  };
  for (const r of ["src", "lib", "tools", "scripts", "overlay", "worker"]) walk(join(ROOT, r));
  if (out.length === 0) {
    for (const e of readdirSafe(ROOT)) {
      if (/\.(ts|js|mjs|cjs)$/.test(e) && !/\.(test|spec|config)\./.test(e))
        out.push(join(ROOT, e));
    }
  }
  return out;
}
function readSrcText(): string[] {
  return collectSrc().map((f) => {
    try {
      return readFileSync(f, "utf8");
    } catch {
      return "";
    }
  });
}

describe("sigmashake-vcs failover — graceful-degradation paths exist", () => {
  test("source carries error handling or fallback constructs", () => {
    const src = readSrcText().join("\n");
    if (src.trim().length === 0) return;
    expect(/\b(try|catch|onError|finally|fallback|retry|rescue)\b|\.catch\(/.test(src)).toBe(true);
  });
});
