// sigmashake-vcs — regression test
// Regression — the public script surface is pinned against drift.
// Generated by shared/agent-config/scripts/generate-kind-tests.ts — runtime-free:
// asserts invariants from the project's own files (deterministic, PSU-safe).
import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");

function readJson(p: string) {
  const raw = readFileSync(p, "utf8");
  return JSON.parse(raw);
}
function pkg() {
  return readJson(join(ROOT, "package.json"));
}

describe("sigmashake-vcs regression — public script surface is stable", () => {
  test("retains a test script", () => {
    const sc = pkg().scripts || {};
    expect(Object.keys(sc).some((k) => k === "test" || k.startsWith("test:"))).toBe(true);
  });
  test("package name keeps its expected shape", () => {
    const n = pkg().name || "";
    expect(/^(@[\w-]+\/[\w.-]+|[\w.-]+)$/.test(n)).toBe(true);
  });
});
