// sigmashake-vcs — component test
// Component — every source module is non-empty real code in isolation.
// Generated by shared/agent-config/scripts/generate-kind-tests.ts — runtime-free:
// asserts invariants from the project's own files (deterministic, PSU-safe).
import { describe, expect, test } from "bun:test";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");

function readdirSafe(d: string): string[] {
  try {
    return readdirSync(d);
  } catch {
    return [];
  }
}
function collectSrc(): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const e of readdirSafe(dir)) {
      if (e === "node_modules" || e === "dist" || e === "public" || e.startsWith(".")) continue;
      const full = join(dir, e);
      let isDir = false;
      try {
        isDir = statSync(full).isDirectory();
      } catch {
        continue;
      }
      if (isDir) walk(full);
      else if (/\.(ts|tsx|js|mjs|cjs)$/.test(full) && !/\.(test|spec)\./.test(full)) out.push(full);
    }
  };
  for (const r of ["src", "lib", "tools", "scripts", "overlay", "worker"]) walk(join(ROOT, r));
  if (out.length === 0) {
    for (const e of readdirSafe(ROOT)) {
      if (/\.(ts|js|mjs|cjs)$/.test(e) && !/\.(test|spec|config)\./.test(e))
        out.push(join(ROOT, e));
    }
  }
  return out;
}

describe("sigmashake-vcs component — source modules are individually well-formed", () => {
  const files = collectSrc();
  test("has at least one source module", () => {
    expect(files.length).toBeGreaterThan(0);
  });
  test("every source module is non-empty and contains real code constructs", () => {
    const bad: string[] = [];
    for (const f of files) {
      const t = readFileSync(f, "utf8").trim();
      if (t.length === 0) {
        bad.push(`${f} (empty)`);
        continue;
      }
      if (f.endsWith(".d.ts")) continue; // ambient type-declaration file: non-empty is enough
      const code = t
        .replace(/\/\*[\s\S]*?\*\//g, "")
        .replace(/(^|[^:])\/\/[^\n]*/g, "$1")
        .trim();
      if (code.length === 0) continue; // comment-only placeholder (e.g. auto-generated config stub)
      if (
        !/\b(import|export|function|const|let|var|class|return|declare|interface|type|enum|namespace)\b|=>|module\.exports|window\.|globalThis\./.test(
          code,
        )
      ) {
        bad.push(`${f} (no code construct)`);
      }
    }
    expect(bad).toEqual([]);
  });
});
