// sigmashake-vcs — pen test
// Pen — no high-risk injection sinks (shell/dynamic-code from interpolated input).
// Generated by shared/agent-config/scripts/generate-kind-tests.ts — runtime-free:
// asserts invariants from the project's own files (deterministic, PSU-safe).
import { describe, expect, test } from "bun:test";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");

function readdirSafe(d: string): string[] {
  try {
    return readdirSync(d);
  } catch {
    return [];
  }
}
function collectSrc(): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const e of readdirSafe(dir)) {
      if (e === "node_modules" || e === "dist" || e === "public" || e.startsWith(".")) continue;
      const full = join(dir, e);
      let isDir = false;
      try {
        isDir = statSync(full).isDirectory();
      } catch {
        continue;
      }
      if (isDir) walk(full);
      else if (/\.(ts|tsx|js|mjs|cjs)$/.test(full) && !/\.(test|spec)\./.test(full)) out.push(full);
    }
  };
  for (const r of ["src", "lib", "tools", "scripts", "overlay", "worker"]) walk(join(ROOT, r));
  if (out.length === 0) {
    for (const e of readdirSafe(ROOT)) {
      if (/\.(ts|js|mjs|cjs)$/.test(e) && !/\.(test|spec|config)\./.test(e))
        out.push(join(ROOT, e));
    }
  }
  return out;
}
function securitySrc(): string[] {
  return collectSrc().filter((f) => !f.replace(/\\/g, "/").includes("/scripts/"));
}

describe("sigmashake-vcs pen — no high-risk injection sinks", () => {
  // Negative lookbehind for "." excludes method calls such as db.exec() (SQLite);
  // only standalone shell-exec / dynamic-code sinks fed from an interpolated
  // string template are flagged. Patterns kept as literals — the "(" is always
  // preceded by an escaped metachar, so the banned call tokens never appear.
  const SINKS: Array<{ name: string; re: RegExp }> = [
    { name: "shell-exec-template", re: /(?<![.\w])exec(Sync)?\s*\(\s*[`'"][^`'"]*\$\{/ },
    {
      name: "function-ctor-concat",
      re: /(?<![.\w])Function\s*\([^)]*\+\s*(req|input|body|params|query)/,
    },
    { name: "dynamic-code-userinput", re: /(?<![.\w])eval\s*\(\s*(req|input|body|params|query)\b/ },
  ];
  test("source carries no shell/dynamic-code sink fed from interpolated input", () => {
    const hits: string[] = [];
    for (const f of securitySrc()) {
      const t = readFileSync(f, "utf8");
      for (const sink of SINKS) if (sink.re.test(t)) hits.push(`${f} :: ${sink.name}`);
    }
    expect(hits).toEqual([]);
  });
});
