// sigmashake-vcs — scalability test
// Scalability — processing scales linearly with input size (pure invariant).
// Generated by shared/agent-config/scripts/generate-kind-tests.ts — runtime-free:
// asserts invariants from the project's own files (deterministic, PSU-safe).
import { describe, expect, test } from "bun:test";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");

function readdirSafe(d: string): string[] {
  try {
    return readdirSync(d);
  } catch {
    return [];
  }
}
function collectSrc(): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const e of readdirSafe(dir)) {
      if (e === "node_modules" || e === "dist" || e === "public" || e.startsWith(".")) continue;
      const full = join(dir, e);
      let isDir = false;
      try {
        isDir = statSync(full).isDirectory();
      } catch {
        continue;
      }
      if (isDir) walk(full);
      else if (/\.(ts|tsx|js|mjs|cjs)$/.test(full) && !/\.(test|spec)\./.test(full)) out.push(full);
    }
  };
  for (const r of ["src", "lib", "tools", "scripts", "overlay", "worker"]) walk(join(ROOT, r));
  if (out.length === 0) {
    for (const e of readdirSafe(ROOT)) {
      if (/\.(ts|js|mjs|cjs)$/.test(e) && !/\.(test|spec|config)\./.test(e))
        out.push(join(ROOT, e));
    }
  }
  return out;
}
function readSrcText(): string[] {
  return collectSrc().map((f) => {
    try {
      return readFileSync(f, "utf8");
    } catch {
      return "";
    }
  });
}
function digest(s: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = (h * 0x01000193) >>> 0;
  }
  return h >>> 0;
}

describe("sigmashake-vcs scalability — linear scaling invariant", () => {
  test("doubling the input doubles processed length; digest output stays O(1)", () => {
    const unit = (readSrcText()[0] || "sigmashake-vcs-unit").slice(0, 1024) || "x";
    expect((unit + unit).length).toBe(unit.length * 2);
    expect(String(digest(unit)).length).toBeLessThanOrEqual(10);
    expect(String(digest(unit + unit)).length).toBeLessThanOrEqual(10);
  });
});
