// sigmashake-vcs — chaos test
// Chaos — malformed inputs fail gracefully; config survives surrounding chaos.
// Generated by shared/agent-config/scripts/generate-kind-tests.ts — runtime-free:
// asserts invariants from the project's own files (deterministic, PSU-safe).
import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");

function readJson(p: string) {
  const raw = readFileSync(p, "utf8");
  return JSON.parse(raw);
}
function pkg() {
  return readJson(join(ROOT, "package.json"));
}

describe("sigmashake-vcs chaos — malformed input fails gracefully", () => {
  test("garbage JSON throws but is catchable (no crash)", () => {
    const garbage = ["{", "}{", "\u0000", "[1,2,", '{"a":', "not json at all"];
    for (const g of garbage) {
      let threw = false;
      try {
        JSON.parse(g);
      } catch {
        threw = true;
      }
      expect(threw).toBe(true);
    }
  });
  test("project config still parses amid surrounding chaos", () => {
    expect(() => pkg()).not.toThrow();
  });
});
